export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './authController.serviceInterface';
export * from './empresas.service';
import { EmpresasService } from './empresas.service';
export * from './empresas.serviceInterface';
export * from './fichajes.service';
import { FichajesService } from './fichajes.service';
export * from './fichajes.serviceInterface';
export * from './formasJurdicas.service';
import { FormasJurdicasService } from './formasJurdicas.service';
export * from './formasJurdicas.serviceInterface';
export * from './generos.service';
import { GenerosService } from './generos.service';
export * from './generos.serviceInterface';
export * from './nominas.service';
import { NominasService } from './nominas.service';
export * from './nominas.serviceInterface';
export * from './permisos.service';
import { PermisosService } from './permisos.service';
export * from './permisos.serviceInterface';
export * from './trabajadores.service';
import { TrabajadoresService } from './trabajadores.service';
export * from './trabajadores.serviceInterface';
export * from './usuarioResource.service';
import { UsuarioResourceService } from './usuarioResource.service';
export * from './usuarioResource.serviceInterface';
export const APIS = [AuthControllerService, EmpresasService, FichajesService, FormasJurdicasService, GenerosService, NominasService, PermisosService, TrabajadoresService, UsuarioResourceService];
