/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ActualizarEmpresaDto } from '../model/models';
import { ApiRespuestaBoolean } from '../model/models';
import { ApiRespuestaEmpresaDto } from '../model/models';
import { ApiRespuestaListEmpresaDto } from '../model/models';
import { ApiRespuestaListFichajesDto } from '../model/models';
import { ApiRespuestaListTrabajadorDto } from '../model/models';
import { EmailRequest } from '../model/models';
import { TrabajadorDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EmpresasServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * actualizar datos de una empresa
     * actualizar datos de una empresa
     * @param actualizarEmpresaDto 
     */
    actualizarEmpresa(actualizarEmpresaDto: ActualizarEmpresaDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * actualizar datos de un trabajador
     * actualizar datos de un trabajador
     * @param trabajadorDto 
     */
    actualizarTrabajador1(trabajadorDto: TrabajadorDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * Dar de alta a un trabajador
     * Dar de alta a un trabajador
     * @param trabajadorDto 
     */
    altaTrabajador(trabajadorDto: TrabajadorDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * Dar de baja a un trabajador
     * Dar de baja a un trabajador
     * @param emailRequest 
     */
    bajaTrabajador(emailRequest: EmailRequest, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * Obtener una empresa por email
     * Obtener una empresa por email
     */
    empresaPorEmail(extraHttpRequestParams?: any): Observable<ApiRespuestaEmpresaDto>;

    /**
     * Obtener los fichajes de una empresa por email
     * Obtener los fichajes de una empresa por email
     */
    fichajesPorEmpresa(extraHttpRequestParams?: any): Observable<ApiRespuestaListFichajesDto>;

    /**
     * Obtener listado de empresas
     * Obtener listado de empresas
     */
    listadoEmpresas(extraHttpRequestParams?: any): Observable<ApiRespuestaListEmpresaDto>;

    /**
     * Obtener los trabajadores de una empresa por email
     * Obtener los trabajadores de una empresa por email
     */
    trabajadoresPorEmpresa(extraHttpRequestParams?: any): Observable<ApiRespuestaListTrabajadorDto>;

}
