/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiRespuestaBoolean } from '../model/models';
import { FichajeEditRequestDto } from '../model/models';
import { FichajeRequestDto } from '../model/models';
import { IdRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FichajesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Crear un fichaje
     * Permite a la empresa crear un nuevo fichaje para un trabajador
     * @param fichajeRequestDto 
     */
    crearFichaje(fichajeRequestDto: FichajeRequestDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * Editar un fichaje
     * Permite a la empresa editar un fichaje existente de un trabajador
     * @param fichajeEditRequestDto 
     */
    editarFichaje(fichajeEditRequestDto: FichajeEditRequestDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * Eliminar un fichaje
     * Permite a la empresa eliminar un fichaje de un trabajador mediante su id
     * @param idRequestDto 
     */
    eliminarFichaje(idRequestDto: IdRequestDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * Finalizar fichaje
     * El trabajador cierra su último fichaje abierto mediante su id
     */
    finalizarFichaje(extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * Iniciar fichaje
     * El trabajador inicia su fichaje (solo fechaInicio) mediante su id
     */
    iniciarFichaje(extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

}
