/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiRespuestaListFormaJuridicaDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FormasJurdicasServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Listar formas jurídicas
     * Devuelve todas las formas jurídicas disponibles (id, nombre y código)
     */
    listarFormasJuridicas(extraHttpRequestParams?: any): Observable<ApiRespuestaListFormaJuridicaDto>;

}
