/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiRespuestaListGeneroDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GenerosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Listar géneros
     * Devuelve todos los géneros disponibles (id, nombre y código)
     */
    listarGeneros(extraHttpRequestParams?: any): Observable<ApiRespuestaListGeneroDto>;

}
