/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiRespuestaBoolean } from '../model/models';
import { ApiRespuestaListNominaMetadataDto } from '../model/models';
import { IdRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface NominasServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Descargar una nómina
     * Permite descargar el PDF de una nómina dada su id
     * @param idRequestDto 
     */
    descargarNomina(idRequestDto: IdRequestDto, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * Eliminar una nómina
     * Permite a la empresa eliminar una nómina de la base de datos mediante su id usando POST
     * @param idRequestDto 
     */
    eliminarNomina(idRequestDto: IdRequestDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * Listar períodos de nóminas de un trabajador
     * Devuelve una lista con id y periodo de todas las nóminas subidas para un trabajador
     * @param idRequestDto 
     */
    listarNominasDeTrabajador(idRequestDto: IdRequestDto, extraHttpRequestParams?: any): Observable<ApiRespuestaListNominaMetadataDto>;

    /**
     * Listar períodos de nóminas de un trabajador
     * Devuelve una lista con id y periodo de todas las nóminas subidas para un trabajador
     */
    listarNominasDeTrabajadorPorEmail(extraHttpRequestParams?: any): Observable<ApiRespuestaListNominaMetadataDto>;

    /**
     * Subir una nómina
     * Permite a la empresa subir una nómina en formato PDF para un trabajador
     * @param trabajadorId 
     * @param periodo 
     * @param file 
     */
    subirNomina(trabajadorId: number, periodo: string, file: Blob, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

}
