/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiRespuestaBoolean } from '../model/models';
import { ApiRespuestaListPermisosDto } from '../model/models';
import { ApiRespuestaListTipoPermisoDto } from '../model/models';
import { IdRequestDto } from '../model/models';
import { PermisoEditarDto } from '../model/models';
import { PermisoSolicitarDto } from '../model/models';
import { PermisoValidarDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PermisosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Editar permiso
     * El trabajador edita un permiso si sigue en estado SOLICITADO
     * @param permisoEditarDto 
     */
    editar(permisoEditarDto: PermisoEditarDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * Eliminar permiso
     * Permite al trabajador eliminar un permiso si aún está en estado SOLICITADO
     * @param idRequestDto 
     */
    eliminarPermiso(idRequestDto: IdRequestDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * Listar tipos de permiso
     * Devuelve todos los tipos de permiso disponibles (id, nombre y código)
     */
    listarTiposPermiso(extraHttpRequestParams?: any): Observable<ApiRespuestaListTipoPermisoDto>;

    /**
     * Permisos de todos los trabajadores por el id de la empresa
     * Devuelve todos los permisos de los trabajadores  por el id de la empresa
     */
    permisosPorEmpresaId(extraHttpRequestParams?: any): Observable<ApiRespuestaListPermisosDto>;

    /**
     * Permisos de un trabajador
     * Devuelve todos los permisos de un trabajador por su id
     */
    permisosPorTrabajadorId(extraHttpRequestParams?: any): Observable<ApiRespuestaListPermisosDto>;

    /**
     * Solicitar permiso
     * El trabajador solicita un permiso
     * @param permisoSolicitarDto 
     */
    solicitar(permisoSolicitarDto: PermisoSolicitarDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * Validar permiso
     * La empresa aprueba o rechaza un permiso
     * @param permisoValidarDto 
     */
    validar(permisoValidarDto: PermisoValidarDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

}
