/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ActualizarTrabajadorDto } from '../model/models';
import { ApiRespuestaBoolean } from '../model/models';
import { ApiRespuestaListFichajesDto } from '../model/models';
import { ApiRespuestaTrabajadorDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TrabajadoresServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * actualizar datos de un trabajador
     * actualizar datos de un trabajador
     * @param actualizarTrabajadorDto 
     */
    actualizarTrabajador(actualizarTrabajadorDto: ActualizarTrabajadorDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * Obtener los fichajes de un trabajador por email
     * Obtener los fichajes de un trabajador por email
     */
    fichajesPorEmailTrabajador(extraHttpRequestParams?: any): Observable<ApiRespuestaListFichajesDto>;

    /**
     * Obtener los datos de un trabajador por email
     * Obtener los datos de un trabajador por email
     */
    obtenerTrabajador(extraHttpRequestParams?: any): Observable<ApiRespuestaTrabajadorDto>;

}
