/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarTrabajadorDto { 
    nombre?: string;
    apellidos?: string;
    genero?: ActualizarTrabajadorDto.GeneroEnum;
    dni?: string;
    iban?: string;
    fechaNacimiento?: string;
    telefono?: number;
    email?: string;
    passwordAntigua?: string;
    passwordNueva?: string;
}
export namespace ActualizarTrabajadorDto {
    export type GeneroEnum = 'FEMENINO' | 'MASCULINO' | 'NO_DETERMINADO';
    export const GeneroEnum = {
        Femenino: 'FEMENINO' as GeneroEnum,
        Masculino: 'MASCULINO' as GeneroEnum,
        NoDeterminado: 'NO_DETERMINADO' as GeneroEnum
    };
}


