/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarEmpresaDto { 
    nombre?: string;
    formaJuridica?: ActualizarEmpresaDto.FormaJuridicaEnum;
    cif?: string;
    direccion?: string;
    telefono?: number;
    email?: string;
    passwordAntigua?: string;
    passwordNueva?: string;
}
export namespace ActualizarEmpresaDto {
    export type FormaJuridicaEnum = 'AUTONOMO' | 'SOCIEDAD_LIMITADA' | 'SOCIEDAD_ANONIMA' | 'COOPERATIVA';
    export const FormaJuridicaEnum = {
        Autonomo: 'AUTONOMO' as FormaJuridicaEnum,
        SociedadLimitada: 'SOCIEDAD_LIMITADA' as FormaJuridicaEnum,
        SociedadAnonima: 'SOCIEDAD_ANONIMA' as FormaJuridicaEnum,
        Cooperativa: 'COOPERATIVA' as FormaJuridicaEnum
    };
}


