/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermisosDto } from './permisosDto';


/**
 * Respuestas estandarizadas de la api
 */
export interface ApiRespuestaListPermisosDto { 
    data?: Array<PermisosDto>;
    estado?: ApiRespuestaListPermisosDto.EstadoEnum;
}
export namespace ApiRespuestaListPermisosDto {
    export type EstadoEnum = 'exito' | 'error';
    export const EstadoEnum = {
        Exito: 'exito' as EstadoEnum,
        Error: 'error' as EstadoEnum
    };
}


