/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FichajesDto } from './fichajesDto';


/**
 * Respuestas estandarizadas de la api
 */
export interface ApiRespuestaListFichajesDto { 
    data?: Array<FichajesDto>;
    estado?: ApiRespuestaListFichajesDto.EstadoEnum;
}
export namespace ApiRespuestaListFichajesDto {
    export type EstadoEnum = 'exito' | 'error';
    export const EstadoEnum = {
        Exito: 'exito' as EstadoEnum,
        Error: 'error' as EstadoEnum
    };
}


