/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormaJuridicaDto } from './formaJuridicaDto';


/**
 * Respuestas estandarizadas de la api
 */
export interface ApiRespuestaListFormaJuridicaDto { 
    data?: Array<FormaJuridicaDto>;
    estado?: ApiRespuestaListFormaJuridicaDto.EstadoEnum;
}
export namespace ApiRespuestaListFormaJuridicaDto {
    export type EstadoEnum = 'exito' | 'error';
    export const EstadoEnum = {
        Exito: 'exito' as EstadoEnum,
        Error: 'error' as EstadoEnum
    };
}


