/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NominaMetadataDto } from './nominaMetadataDto';


/**
 * Respuestas estandarizadas de la api
 */
export interface ApiRespuestaListNominaMetadataDto { 
    data?: Array<NominaMetadataDto>;
    estado?: ApiRespuestaListNominaMetadataDto.EstadoEnum;
}
export namespace ApiRespuestaListNominaMetadataDto {
    export type EstadoEnum = 'exito' | 'error';
    export const EstadoEnum = {
        Exito: 'exito' as EstadoEnum,
        Error: 'error' as EstadoEnum
    };
}


