/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TipoPermisoDto } from './tipoPermisoDto';


/**
 * Respuestas estandarizadas de la api
 */
export interface ApiRespuestaListTipoPermisoDto { 
    data?: Array<TipoPermisoDto>;
    estado?: ApiRespuestaListTipoPermisoDto.EstadoEnum;
}
export namespace ApiRespuestaListTipoPermisoDto {
    export type EstadoEnum = 'exito' | 'error';
    export const EstadoEnum = {
        Exito: 'exito' as EstadoEnum,
        Error: 'error' as EstadoEnum
    };
}


