/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpresaDto } from './empresaDto';


/**
 * Respuestas estandarizadas de la api
 */
export interface ApiRespuestaEmpresaDto { 
    data?: EmpresaDto;
    estado?: ApiRespuestaEmpresaDto.EstadoEnum;
}
export namespace ApiRespuestaEmpresaDto {
    export type EstadoEnum = 'exito' | 'error';
    export const EstadoEnum = {
        Exito: 'exito' as EstadoEnum,
        Error: 'error' as EstadoEnum
    };
}


