/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmpresaDto { 
    id?: number;
    nombre?: string;
    formaJuridica?: EmpresaDto.FormaJuridicaEnum;
    cif?: string;
    direccion?: string;
    telefono?: number;
    email?: string;
    password?: string;
    rol?: EmpresaDto.RolEnum;
    activo?: boolean;
}
export namespace EmpresaDto {
    export type FormaJuridicaEnum = 'AUTONOMO' | 'SOCIEDAD_LIMITADA' | 'SOCIEDAD_ANONIMA' | 'COOPERATIVA';
    export const FormaJuridicaEnum = {
        Autonomo: 'AUTONOMO' as FormaJuridicaEnum,
        SociedadLimitada: 'SOCIEDAD_LIMITADA' as FormaJuridicaEnum,
        SociedadAnonima: 'SOCIEDAD_ANONIMA' as FormaJuridicaEnum,
        Cooperativa: 'COOPERATIVA' as FormaJuridicaEnum
    };
    export type RolEnum = 'ADMIN' | 'EMPRESA' | 'TRABAJADOR';
    export const RolEnum = {
        Admin: 'ADMIN' as RolEnum,
        Empresa: 'EMPRESA' as RolEnum,
        Trabajador: 'TRABAJADOR' as RolEnum
    };
}


