/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PermisoValidarDto { 
    id: number;
    estado: PermisoValidarDto.EstadoEnum;
}
export namespace PermisoValidarDto {
    export type EstadoEnum = 'SOLICITADO' | 'APROBADO' | 'RECHAZADO';
    export const EstadoEnum = {
        Solicitado: 'SOLICITADO' as EstadoEnum,
        Aprobado: 'APROBADO' as EstadoEnum,
        Rechazado: 'RECHAZADO' as EstadoEnum
    };
}


